% Generated by MATLAB(R) 24.2 (R2024b) and LTE Toolbox 24.2 (R2024b).
% matlab -nodisplay -nodesktop -nosplash -r "run('LTE_Uplink_RMC.m');exit;"


%% Generating Uplink RMC waveform

fprintf('Uplink RMC configuration\n');
cfg = struct('RC', 'A1-1', ...
    'NULRB', 100, ...
    'DuplexMode', 'FDD', ...
    'NCellID', 0, ...
    'RNTI', 1, ...
    'TotSubframes', 10, ...
    'Windowing', 0);

cfg.PUSCH.RVSeq = [0 2 3 1];
cfg = lteRMCUL(cfg);

fprintf('Input bit source\n');
in = [1; 0; 0; 1];

fprintf('Generation\n');
[waveform, grid, cfg] = lteRMCULTool(cfg, in);

Fs = cfg.SamplingRate;
fprintf('Sample rate %f Hz\n', Fs);


%% Impairments

fprintf('IQ imbalance\n');
waveform = iqimbal(waveform, 8, (180/pi)*pi/5);

fprintf('Phase noise\n');
phaseNoise = comm.PhaseNoise('FrequencyOffset', [6144000 12288000], ...
    'Level', [-60 -80], ...
    'SampleRate', Fs);
waveform = phaseNoise(waveform);

fprintf('DC offset\n');
waveform = waveform + 0.1 + 0.2i;

fprintf('AWGN\n');
waveform = awgn(waveform, 20, 'measured');


%% Output

fprintf('Exporting\n');
fid = fopen('LTE__Uplink_RMC_waveform.asc', 'w');
fprintf(fid, '%.4f + %.4fi\n', [real(waveform(:)), imag(waveform(:))].');
fclose(fid);

timeScope = timescope('SampleRate', Fs, ...
    'TimeSpanOverrunAction', 'scroll', ...
    'TimeSpanSource', 'property', ...
    'TimeSpan', 9.7656e-07);
timeScope(waveform);
release(timeScope);

spectrum = spectrumAnalyzer('SampleRate', Fs);
spectrum(waveform);
release(spectrum);

fprintf('Done\n');
