% Generated by MATLAB(R) 24.2 (R2024b) and LTE Toolbox 24.2 (R2024b).
% Generated on: 04-Oct-2024 03:39:40

% Chris: Taken from https://www.mathworks.com/help/lte/ref/ltewaveformgenerator-app.html

%% Generating Uplink RMC waveform
% Uplink RMC configuration
cfg = struct('RC', 'A1-1', ...
    'NULRB', 100, ...
    'DuplexMode', 'FDD', ...
    'NCellID', 0, ...
    'RNTI', 1, ...
    'TotSubframes', 10, ...
    'Windowing', 0)

cfg.PUSCH.RVSeq = [0 2 3 1]
cfg = lteRMCUL(cfg)

% input bit source:
in = [1; 0; 0; 1]

% Generation
[waveform, grid, cfg] = lteRMCULTool(cfg, in)

% Specify the sample rate of the waveform in Hz
Fs = cfg.SamplingRate

%% Impairments
% IQ imbalance
waveform = iqimbal(waveform, 8, (180/pi)*pi/5)

% Phase noise
phaseNoise = comm.PhaseNoise('FrequencyOffset', [6144000 12288000], ...
    'Level', 					[-60 -80], ...
    'SampleRate', 			Fs)
waveform = phaseNoise(waveform)

% DC offset
waveform = waveform + 0.1+0.2i

% AWGN
waveform = awgn(waveform, 20, 'measured')

fid = fopen('LTE_Upload_RMC_waveform_data.ascii', 'w')
fprintf(fid, '%.4f + %.4fi\n', real(waveform), imag(waveform))
fclose(fid)

%% Visualize
% Time Scope
%timeScope = timescope('SampleRate', Fs, ...
%    'TimeSpanOverrunAction', 'scroll', ...
%    'TimeSpanSource', 'property', ...
%    'TimeSpan', 9.7656e-07)
%timeScope(waveform)
%release(timeScope)
%
%% Spectrum Analyzer
%spectrum = spectrumAnalyzer('SampleRate', Fs)
%spectrum(waveform)
%release(spectrum)
